name: Olympic Schedule Next App CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types:
      [
        "opened",
        "edited",
        "reopened",
        "labeled",
        "unlabeled",
        "ready_for_review",
      ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm i
      - run: npm run build --if-present

  automerge:
    runs-on: self-hosted

    needs: [build]

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""

  publish:
    runs-on: self-hosted

    needs: [automerge]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push React Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/third-dimension:olympic-schedule-next-app
